# Generated by Django 5.0.2 on 2024-02-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FangListings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField()),
                ('agent_id', models.IntegerField()),
                ('mls_number', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('location_id', models.IntegerField()),
                ('price', models.CharField(max_length=200)),
                ('sold_status', models.CharField(max_length=200)),
                ('market_date', models.CharField(max_length=200)),
                ('year_built', models.CharField(max_length=200)),
                ('last_updated', models.CharField(max_length=200)),
                ('property_type_id', models.IntegerField()),
                ('home_size', models.IntegerField()),
                ('lot_size', models.FloatField()),
                ('beds', models.IntegerField()),
                ('baths', models.FloatField()),
                ('feature_id', models.IntegerField()),
                ('dist_id', models.IntegerField()),
            ],
        ),
    ]
