# Generated by Django 5.0.2 on 2024-03-12 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_fanglistings_listing_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agentid', models.IntegerField(db_column='agentID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('license_field', models.CharField(db_column='license#', max_length=45)),
            ],
            options={
                'db_table': 'agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('listingid', models.IntegerField(db_column='listingID', primary_key=True, serialize=False)),
                ('mls_field', models.CharField(db_column='mls#', max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('soldstatus', models.CharField(db_column='soldStatus', max_length=45)),
                ('marketdate', models.CharField(db_column='marketDate', max_length=45)),
                ('yearbuilt', models.CharField(db_column='yearBuilt', max_length=45)),
                ('lastupdated', models.CharField(db_column='lastUpdated', max_length=45)),
                ('homesize', models.IntegerField(db_column='homeSize')),
                ('lotsize', models.FloatField(db_column='lotSize')),
                ('beds', models.IntegerField()),
                ('baths', models.FloatField()),
                ('featureid', models.IntegerField(blank=True, db_column='featureID', null=True)),
                ('distid', models.IntegerField(db_column='distID')),
            ],
            options={
                'db_table': 'listings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('featureid', models.IntegerField(db_column='featureID', primary_key=True, serialize=False)),
                ('featuredescription', models.TextField(db_column='featureDescription')),
            ],
            options={
                'db_table': 'features',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomepageFanglistings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('agent_id', models.IntegerField()),
                ('mls_number', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('location_id', models.IntegerField()),
                ('price', models.CharField(max_length=200)),
                ('sold_status', models.CharField(max_length=200)),
                ('market_date', models.CharField(max_length=200)),
                ('year_built', models.CharField(max_length=200)),
                ('last_updated', models.CharField(max_length=200)),
                ('property_type_id', models.IntegerField()),
                ('home_size', models.IntegerField()),
                ('lot_size', models.FloatField()),
                ('beds', models.IntegerField()),
                ('baths', models.FloatField()),
                ('feature_id', models.IntegerField()),
                ('dist_id', models.IntegerField()),
            ],
            options={
                'db_table': 'homepage_fanglistings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageid', models.AutoField(db_column='imageID', primary_key=True, serialize=False)),
                ('imagepath', models.CharField(db_column='ImagePath', max_length=45)),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.IntegerField(db_column='locationID', primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('county', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propertytype',
            fields=[
                ('propertytypeid', models.IntegerField(db_column='propertyTypeID', primary_key=True, serialize=False)),
                ('propertytype', models.CharField(db_column='propertyType', max_length=45)),
            ],
            options={
                'db_table': 'propertytype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schooldist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distid', models.IntegerField(blank=True, db_column='distID', null=True)),
                ('distname', models.CharField(blank=True, db_column='distName', max_length=80, null=True)),
            ],
            options={
                'db_table': 'schooldist',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='fanglistings',
            name='baths',
        ),
        migrations.RemoveField(
            model_name='fanglistings',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='fanglistings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fanglistings',
            name='dist_id',
        ),
        migrations.RemoveField(
            model_name='fanglistings',
            name='feature_id',
        ),
        migrations.RemoveField(
            model_name='fanglistings',
            name='home_size',
        ),
        migrations.RemoveField(
            model_name='fanglistings',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='fanglistings',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='fanglistings',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='fanglistings',
            name='market_date',
        ),
        migrations.RemoveField(
            model_name='fanglistings',
            name='mls_number',
        ),
        migrations.RemoveField(
            model_name='fanglistings',
            name='price',
        ),
        migrations.RemoveField(
            model_name='fanglistings',
            name='property_type_id',
        ),
        migrations.RemoveField(
            model_name='fanglistings',
            name='sold_status',
        ),
        migrations.RemoveField(
            model_name='fanglistings',
            name='title',
        ),
        migrations.RemoveField(
            model_name='fanglistings',
            name='year_built',
        ),
        migrations.CreateModel(
            name='Featuredlistings',
            fields=[
                ('listingid', models.OneToOneField(db_column='listingID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='homepage.listings')),
            ],
            options={
                'db_table': 'featuredlistings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listingfeatures',
            fields=[
                ('featureid', models.OneToOneField(db_column='FeatureID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='homepage.features')),
            ],
            options={
                'db_table': 'listingfeatures',
                'managed': False,
            },
        ),
    ]
