# Generated by Django 5.0.2 on 2024-04-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_agent_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FangListings',
        ),
    ]
