# Generated by Django 5.0.2 on 2024-08-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_listingimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='C:/projects/senior project/backendDesign/homepage/static/img'),
        ),
    ]
